version: '3.5'
services:
  build-toolkit:
      build: 
        context: ./docker/build
        # dockerfile: Dockerfile.go1.17.5-bullseye
      working_dir: /var/www
      volumes:
        - ./src:/var/www