# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        run: |
          DOCKER_RELEASE_TAG="tomhjx/hugo:0.92.0"
          docker build ${{ github.workspace }}/docker/build -t $DOCKER_RELEASE_TAG
          docker push $DOCKER_RELEASE_TAG

  build-site:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build
        run: |
          docker run \
          -v ./public:/var/www/public \
          -v ./src/config.yaml:/var/www/config.yaml \
          -v ./src/archetypes:/var/www/archetypes \
          tomhjx/hugo:0.92.0 hugo --minify -t hugo-book
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: tomhjx/www.toolkit
          publish_branch: main
          publish_dir: ./public


